#!/bin/sh
read method path rest || exit
url="https://frinkiac.com/meme/S07E05/296228.jpg?b64lines="
name="$(echo "${path#/}" | tr a-z A-Z)"
base64="$(cat <<MESSAGE | base64 -i -w 0
 P-P-PLEASE, $name, I
 THOUGHT YOU L-L-LOVED ME,
 L-L-LOVED ME.
MESSAGE
)"

if test -n "$REDIRECT" && test "$method" != "X-GET"
then
cat <<RESPONSE
HTTP/1.1 301 OK
Content-Length: 0
Location: $url$base64
Connection: close

RESPONSE
else curl -si "$url$base64"
fi
